backend:
  name: github
  repo: DanPurdy/netlify-blog
  branch: main

publish_mode: editorial_workflow
media_folder: content/assets
public_folder: assets
site_url: https://dpurdy.me

collections:
  - name: pages
    label: Pages
    files:
      - name: personal_details
        label: Personal Details
        file: content/personal_details.md
        fields:
          - { name: title, label: Title }
          - { name: subtitle, label: Sub Title }
          - { name: body, label: Body, widget: markdown }
  - name: experience
    label: Experience
    folder: content/experience
    media_folder: ''
    create: true
    fields:
      - { name: id, label: ID }
      - { name: title, label: Title }
      - { name: url, label: URL }
      - {
          name: logo,
          label: Logo,
          widget: image,
          media_library: { config: { multple: false } },
        }
      - {
          name: startDate,
          label: Start Date,
          widget: datetime,
          timeFormat: false,
          dateFormat: MMM YYYY,
        }
      - { name: isCurrent, label: isCurrent, widget: boolean, required: false }
      - {
          name: endDate,
          label: End Date,
          widget: datetime,
          timeFormat: false,
          dateFormat: MMM YYYY,
        }
      - {
          name: position,
          label: Position,
          widget: list,
          field: { name: position_item, label: Position },
        }
      - {
          name: previousPosition,
          label: Previous Positions,
          widget: list,
          field: { name: position_item, label: Position },
        }
      - { name: body, label: Body, widget: markdown }
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/blog
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields:
      - { name: path, label: Path }
      - {
          name: date,
          label: Date,
          widget: datetime,
          timeFormat: false,
          dateFormat: DD/MM/YYYY,
        }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
