backend:
  name: github
  repo: DanPurdy/netlify-blog
  branch: develop

media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: Pages
    files:
      - name: personal_details
        label: Personal Details
        file: content/personal_details.md
        fields:
          - { name: title, label: Title }
          - { name: subtitle, label: Sub Title }
          - { name: body, label: Body, widget: markdown }
  - name: experience
    label: Experience
    folder: content/experience
    create: true
    fields:
      - { name: id, label: ID }
      - {
          name: startDate,
          label: Start Date,
          widget: datetime,
          timeFormat: false,
          dateFormat: MMM YYYY,
        }
      - {
          name: endDate,
          label: End Date,
          widget: datetime,
          timeFormat: false,
          dateFormat: MMM YYYY,
        }
      - { name: isCurrent, label: isCurrent, widget: boolean, required: false }
      - { name: title, label: Title }
      - { name: position, label: Position, widget: list }
      - { name: previousPosition, label: Previous Positions, widget: list }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: title, label: Title }
      - label: Company
        name: company
        widget: relation
        collection: experience
        searchFields: [id]
        valueField: id
        displayFields: [title]
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - {
          name: date,
          label: Date,
          widget: datetime,
          timeFormat: false,
          dateFormat: DD/MM/YYYY,
        }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
